using AutoMapper;
using MovieAPI.Contracts;
using MovieAPI.Models;

namespace MovieAPI.MappingProfiles
{
    public class AutoMapperProfile : Profile
    {
        public AutoMapperProfile()
        {
            // Map RegisterUserRequest DTO to User entity
            CreateMap<RegisterUserRequest, User>()
                .ForMember(dest => dest.Id, opt => opt.Ignore())       // Id generated by backend/DB
                .ForMember(dest => dest.Role, opt => opt.Ignore())     // Default role set in entity
                .ForMember(dest => dest.Password, opt => opt.MapFrom(src => src.Password)); // map password directly

                        // Map User entity to UserResponseDto (exclude password)
            CreateMap<User, UserResponseDto>()
                .ForMember(dest => dest.Role, opt => opt.MapFrom(src => src.Role.ToString()));

            // Map Review entity to ReviewResponseDto
            CreateMap<Review, ReviewResponseDto>();
        }
    }
}